apiVersion: v1
kind: Service
metadata:
  labels:
    api: serving
  name: serving
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    api: serving
  type: LoadBalancer
