apiVersion: v1
kind: Service
metadata:
  name: worker1
  labels:
    node: worker1
spec:
  type: ClusterIP
  selector:
    node: worker1
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    